packages:
  - "."

allowBuilds:
  core-js: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  workerd: true

overrides:
  vite: 8.2.2

minimumReleaseAgeExclude:
  - astro@7.3.1
  - happy-dom@20.14.0
  - posthog-js@1.427.3
  - vitest@5.0.0
  - vite@8.2.2
  - wrangler@4.129.0
  - zod@4.5.4
  - '@posthog/browser-common@0.7.3'
  - '@posthog/core@1.50.6'
  - '@posthog/types@1.409.1'
  - node-html-parser@9.0.4
