import { existsSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { ALLOWED_USER_AGENTS, buildRobotsTxt } from "@/utils/robots";

const robots = buildRobotsTxt("https://ta93abe.com/");

function allowsRoot(userAgent: string): boolean {
	const escaped = userAgent.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
	return new RegExp(
		`User-agent:\\s*${escaped}\\r?\\nAllow:\\s*/\\s*(?:\\n|$)`,
	).test(robots);
}

describe("robots.txt", () => {
	it("is generated by the Worker, not a static public file", () => {
		expect(existsSync(join(process.cwd(), "public/robots.txt"))).toBe(false);
	});

	it("keeps the wildcard crawl allow", () => {
		expect(allowsRoot("*")).toBe(true);
	});

	it("explicitly allows major AI crawlers that look for their own rules", () => {
		expect([...ALLOWED_USER_AGENTS]).toEqual([
			"*",
			"GPTBot",
			"ChatGPT-User",
			"OAI-SearchBot",
			"ClaudeBot",
			"Claude-Web",
			"Google-Extended",
			"PerplexityBot",
			"CCBot",
			"Applebot",
			"Applebot-Extended",
			"Amazonbot",
			"meta-externalagent",
		]);
		for (const userAgent of ALLOWED_USER_AGENTS) {
			expect(allowsRoot(userAgent), userAgent).toBe(true);
		}
	});

	it("does not add Bytespider", () => {
		expect(robots).not.toMatch(/User-agent:\s*Bytespider/i);
	});
});
