/** HTTP `Content-Signal` と同じ値。robots.txt 本文にも載せてクローラが辿れるようにする。 */
export const CONTENT_SIGNAL = "ai-train=no, search=yes, ai-input=yes";

/** 検索・引用・ライブ取得向け。学習可否は Content-Signal の ai-train=no で示す。 */
const ALLOWED_USER_AGENTS = [
	"*",
	"GPTBot",
	"ChatGPT-User",
	"OAI-SearchBot",
	"ClaudeBot",
	"Claude-Web",
	"Claude-SearchBot",
	"Claude-User",
	"Google-Extended",
	"PerplexityBot",
	"CCBot",
	"Applebot",
	"Meta-ExternalFetcher",
] as const;

/** 学習専用 UA / 学習オプトアウト用トークン。Content-Signal: ai-train=no と揃える。 */
const DISALLOWED_TRAINING_USER_AGENTS = [
	"Applebot-Extended",
	"Meta-ExternalAgent",
	"anthropic-ai",
] as const;

export function buildRobotsTxt(siteOrigin: string): string {
	const origin = siteOrigin.replace(/\/+$/, "");
	const allowGroups = ALLOWED_USER_AGENTS.map(
		(agent) => `User-agent: ${agent}\nAllow: /`,
	).join("\n\n");
	const disallowGroups = DISALLOWED_TRAINING_USER_AGENTS.map(
		(agent) => `User-agent: ${agent}\nDisallow: /`,
	).join("\n\n");

	return `# robots.txt
# Generated by the Worker from src/utils/robots.ts.
# 方針: search / ai-input は許容、学習 (ai-train) は拒否。
# HTTP Content-Signal と同じ意味を、学習専用 UA では Disallow で辿れるようにする。

${allowGroups}

# 学習専用 UA / 学習オプトアウト用トークン
${disallowGroups}

Content-Signal: ${CONTENT_SIGNAL}
Sitemap: ${origin}/sitemap-index.xml
`;
}
